version: '2'
services:
  apm-server:
    container_name: apm-server
    expose:
      - '8200'
    ports:
      - 0.0.0.0:8200:8200
    depends_on:
      - elasticsearch
      - elasticsearch2
    build:
      context: .
      dockerfile: ./dockerfiles/apm-server
    volumes:
      - ./config/apm-server.yml:/usr/share/apm-server/apm-server.yml
    networks:
      - esnet
      - default

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 0.0.0.0:9200:9200
    networks:
      - esnet


  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.1
    container_name : kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5601
    ports:
      - 0.0.0.0:5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch
      - elasticsearch2

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
    driver: bridge
